SQL doesn't permit empty string for INT/TIMESTAMP
msimerson/NicTool pull request #268
Opened 2021-07-28 08:30 UTC by adamgoryachev

Fixes #

Changes proposed in this pull request:
Fix the update query so that we will omit fields which do not need a value added, allowing the default SQL value to be applied. SQL no longer permits a string (even the empty string '') for a INT/TIMESTAMP field.

Checklist:
- [ ] docs updated
- [ ] tests updated

2021-09-14 15:04 UTC, msimerson requested changes

2021-09-14 15:04 UTC, msimerson commented on server/lib/NicToolServer/Zone/Record.pm
> +            if( ! $data->{$c}) {
this will make it impossible to have a timestamp of weight of `0`. This check should instead test if `$data->{$c}` is defined and not empty string.

2021-09-14 16:30 UTC, msimerson commented on server/lib/NicToolServer/Zone/Record.pm
> +            if( ! $data->{$c}) {
see also #106

2021-09-17 05:56 UTC, adamgoryachev commented on server/lib/NicToolServer/Zone/Record.pm
> +            if( ! $data->{$c}) {
Hi, new commit completed, hopefully this is good now.

2022-04-12 05:37 UTC, msimerson commented on server/lib/NicToolServer/Zone/Record.pm
> +            if( ! defined $data->{$c} || $data->{$c} == '') {
```suggestion
            if ( $data->{$c} == '' ) {
```

Checking for `! defined $data->{$c}` here is redundant because that check is already performed on line 139, right?

2022-04-30 11:34 UTC, adamgoryachev commented on server/lib/NicToolServer/Zone/Record.pm
> +            if( ! defined $data->{$c} || $data->{$c} == '') {
You are right, it was already checked on line 139. Updated pull request now, let me know if any further changes are needed.

2022-04-30 16:15 UTC, merged